/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./components/Home/Cards.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    NavLinks: typeof import('./components/NavLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Snackbar: typeof import('./components/Snackbar/index.vue')['default']
    StatsPanelList: typeof import('./components/Home/StatsPanelList.vue')['default']
    Toast: typeof import('./components/Toast/index.vue')['default']
    Typography: typeof import('./components/Home/Typography.vue')['default']
  }
}
